# Generated by Django 5.1.4 on 2024-12-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIProcessing', '0002_alter_currentforecast_sunrise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentforecast',
            name='sunrise',
            field=models.TimeField(default='06:00:00'),
        ),
        migrations.AlterField(
            model_name='currentforecast',
            name='sunset',
            field=models.TimeField(default='18:00:00'),
        ),
    ]
