# Generated by Django 5.1.4 on 2024-12-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIProcessing', '0003_alter_currentforecast_sunrise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('days', models.ManyToManyField(to='APIProcessing.currentforecast')),
            ],
        ),
    ]
